# -*- coding: utf-8 -*-
"""eComm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18aM8xvSwwURH7LrkZcyK50u538R8zZlQ
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
file_path = '/content/afame/ECOMM DATA.xlsx'
df = pd.read_excel(file_path)

# Explore the dataset
print(df.head())
print(df.info())

# Data Cleaning
df.dropna(inplace=True)  # Drop rows with missing values
df.drop_duplicates(inplace=True)  # Drop duplicate rows
print(df.head())

# Calculate Total Sales
total_sales = df['Sales'].sum()
print(f'Total Sales: {total_sales}')

# Plot Sales Trends
plt.figure(figsize=(10, 6))
sales_trends.plot()
plt.title('Sales Trends Over Time')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.show()

# Determine Best-Selling Products
best_selling_products = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False)
print(best_selling_products)


# Plot Best-Selling Products
plt.figure(figsize=(10, 6))
best_selling_products.head(10).plot(kind='bar')
plt.title('Top 10 Best-Selling Products')
plt.xlabel('Product Name')
plt.ylabel('Total Sales')
plt.show()